services:
  - type: web
    name: my-chatbot
    env: python
    plan: free
    pythonVersion: "3.10.14"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 7860
